name: Merge, Modify, and Add Logos to M3U Files

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

jobs:
  merge-modify-add-logos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到最新版本

    - name: Set up Python
      uses: actions/setup-python@v3  # 更新到最新版本

    - name: Download M3U Files
      run: |
        curl -o GuangdongIPTV_rtp_4k.m3u https://raw.githubusercontent.com/Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List/master/GuangdongIPTV_rtp_4k.m3u
        curl -o GuangdongIPTV_rtp_hd.m3u https://raw.githubusercontent.com/Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List/master/GuangdongIPTV_rtp_hd.m3u

    - name: Merge, Modify, and Add Logos to M3U Files
      run: |
        python3 merge_and_modify_m3u.py
        ls -l  # 确认tv.m3u文件生成

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add tv.m3u
        git commit -m 'Merged, modified, and added logos to M3U files'
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/eeooeeooee/TV.git
